export const ADD_NEW_ELEMENT = "ADD_NEW_ELEMENT";
export const UPDATE_ELEMENT_INDEX = "UPDATE_ELEMENT_INDEX";
export const UPDATE_MOBILITY = "UPDATE_MOBILITY";
export const RESTART_GAME = "RESTART_GAME";
export const UPDATE_ELEMENT_OFFSET = "UPDATE_ELEMENT_OFFSET";
export const START_GAME = "START_GAME";
export const SET_MOVING_ITEM = "SET_MOVING_ITEM";
